### ISSUE TITLE
怎么修改生成的图片中文字跟边框的距离

### ISSUE THREAD

**Issue by zhyit** [fex-team/kityformula-editor#8]
现在生成的公式图片，文字跟边框的间距太大了，如图：
![image](https://github.com/fex-team/kityformula-editor/assets/43231863/46501f2a-5d61-49d7-bc06-5182278eb141)
我想要的效果是像word那样，几乎没有间距，如同：
![image](https://github.com/fex-team/kityformula-editor/assets/43231863/bd574bdd-a1bb-48a7-a614-81d9e177165b)

**Comment by wentaodeng2017** [comment]
请问你的问题解决了吗？

**Comment by zhyit** [comment]
> 请问你的问题解决了吗？

修改kityformula-editor.all.min.js中的padding值，具体哪个我忘记了，你测试一下吧，我现在不用这个插件了

**Comment by zhyit** [comment]
> > 请问你的问题解决了吗？
> 
> 修改kityformula-editor.all.min.js中的padding值，具体哪个我忘记了，你测试一下吧，我现在不用这个插件了

我现在用的是mathjax
> https://github.com/zhyit/tinymce-plugins/tree/main/mathjax

**Comment by wentaodeng2017** [comment]
> > > 请问你的问题解决了吗？
> > 
> > 
> > 修改kityformula-editor.all.min.js中的padding值，具体哪个我忘记了，你测试一下吧，我现在不用这个插件了
> 
> 我现在用的是mathjax
> 
> > https://github.com/zhyit/tinymce-plugins/tree/main/mathjax

感谢大佬
